commif files

diff --git a/.github/workflows/solar-system-k8s-reusable-wf dirty-copy.yaml b/.github/workflows/solar-system-k8s-reusable-wf dirty-copy.yaml
--- a/.github/workflows/solar-system-k8s-reusable-wf dirty-copy.yaml
+++ b/.github/workflows/solar-system-k8s-reusable-wf dirty-copy.yaml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
   push:
      branches:
-       - main
+       - master
        - feature/**
  
 env:
@@ -31,6 +31,25 @@ jobs:
       uses: actions/setup-node@v5   
       with:                         
         node-version: ${{ matrix.nodejs_version }}
+
+    # - name: Get npm cache directory
+    #   id: npm-cache-dir
+    #   shell: bash
+    #   run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
+
+    # - name: Cache NPM dependency
+    #   uses: actions/cache@v4
+    #   with:
+    #     path: |
+    #       # path where the dependedncy are generally added
+    #       # in our case all the dependencies are downloaded and store din "node_modules" dir
+    #       # node_modules
+    #       # https://github.com/actions/cache/blob/main/examples.md#bash-shell
+    #       ${{ steps.npm-cache-dir.outputs.dir }}
+    #     ### every time the key changes we've to invalidate the cache and create a new key/path pair
+    #     key: ${{ matrix.operating_system }}-node-module-${{ hashFiles('package-lock.json') }}  
+    #     # restore-keys: |
+    #     #   ${{ matrix.operating_system }}-node-module-
         
     - name: Install Dependencies
       run: |
@@ -40,6 +59,14 @@ jobs:
       id: nodejs-unit-testing
       run: |
         npm test
+        # mv test-results.xml test-results-${{ matrix.nodejs_version }}-${{ matrix.operating_system }}.xml
+      
+    # - name: Archive Test Result
+    #   if: always()
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: Mocha-Test-Result-${{ matrix.nodejs_version }}-${{ matrix.operating_system }}
+    #     path: test-results-${{ matrix.nodejs_version }}-${{ matrix.operating_system }}.xml
 
   code-coverage:
     name: Code Coverage
@@ -61,6 +88,25 @@ jobs:
       with:
         node-version: ${{ matrix.nodejs_version }}
 
+    # - name: Get npm cache directory
+    #   id: npm-cache-dir
+    #   shell: bash
+    #   run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
+
+    # - name: Cache NPM dependency
+    #   uses: actions/cache@v4
+    #   with:
+    #     path: |
+    #       # path where the dependedncy are generally added
+    #       # in our case all the dependencies are downloaded and store din "node_modules" dir
+    #       # node_modules
+    #       # https://github.com/actions/cache/blob/main/examples.md#bash-shell
+    #       ${{ steps.npm-cache-dir.outputs.dir }}
+    #     ### every time the key changes it invalidates the cache and it creates a new key/path pair
+    #     key: ${{ matrix.operating_system }}-node-module-${{ hashFiles('package-lock.json') }}  
+    #     # restore-keys: |
+    #     #   ${{ matrix.operating_system }}-node-module-            
+
     - name: Install dependencies
       run: npm install
 
@@ -68,7 +114,28 @@ jobs:
       id: run_coverage
       continue-on-error: true
       run: |
+        # COVERAGE_DIR="${{ matrix.operating_system }}-node-${{ matrix.nodejs_version }}"
+        # echo "coverage_dir=$COVERAGE_DIR" >> $GITHUB_OUTPUT
+        # # echo "Coverage directory: $COVERAGE_DIR"
+        # npx nyc --reporter=lcov --report-dir="$COVERAGE_DIR" npm test
+        
+        # # doesn't work because 'npm run coverage' fails with exit 1 and doesn't run the code below!
+        # # tar -cvzf coverage.tar.gz coverage
+        # # ls -la
         npm test
+        
+    # - name: Compress coverage directory
+    #   run: |
+    #     # echo "Coverage directory: ${{ steps.run_coverage.outputs.coverage_dir }}"
+    #     tar -cvzf ${{ steps.run_coverage.outputs.coverage_dir }}.tar.gz ${{ steps.run_coverage.outputs.coverage_dir }}
+    #     ls -la
+
+    # - name: Archive coverage report
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: Code-Coverage-Result-${{ steps.run_coverage.outputs.coverage_dir }}
+    #     path: ${{ steps.run_coverage.outputs.coverage_dir }}.tar.gz
+    #     retention-days: 5
 
   containerization:
     name: Containerization
@@ -133,6 +200,11 @@ jobs:
         push: true
         tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
 
+    # # instead the previous step we can run the one below, whithout rebuild the image!
+    # - name: Push Docker Image
+    #   run: |
+    #     docker push ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}    
+
   dev-deploy:
     needs: containerization
     if: contains(github.ref, 'feature/')
@@ -150,13 +222,27 @@ jobs:
         with:
           version: 'v1.32.0'
 
+      # - name: Configure kubeconfig context
+      #   uses: azure/k8s-set-context@v3
+      #   with:
+      #     method: kubeconfig
+      #     kubeconfig: ${{ secrets.KUBECONFIG }}
+
       - name: Print kubeconfig secret
         run: |
           echo "Print kubeconfig secret --->${{ secrets.KUBECONFIG }}<--- "
 
+      # - name: Fetch Kubernetes Cluster Details
+      #   run: |
+      #     kubectl version --short
+      #     echo "------------------------------------------"
+      #     kubectl get nodes
+
       - name: Save Nginx Ingress IP
         id: ingress
         run: |
+          # echo "INGRESS_IP=$(kubectl -n ingress-nginx get svc ingress-nginx-controller \
+          #   -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV
           echo "INGRESS_IP=ingres.url" >> $GITHUB_ENV
 
       - name: Replace tokens in manifests
@@ -176,11 +262,27 @@ jobs:
 
       - name: Create MongoDB Secret
         run: |
+          # kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
+          #   --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
+          #   --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
+          #   --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
+          #   --save-config \
+          #   --dry-run=client \
+          #   -o yaml | kubectl apply -f -
+
           echo "-namespace: ${{ vars.NAMESPACE }}\n-mongo uri: ${{ env.MONGO_URI }}\n-mongo username: ${{ env.MONGO_USERNAME }}\n-mongo pwd: ${{ secrets.MONGO_PASSWORD }}\n"
+
+      # - name: Deploy to Dev Environment
+      #   run: |
+      #     kubectl apply -f kubernetes/development     ### deploy everything in dev dir
       
       - name: Set App Ingress Host URL
         id: set-ingress-host-address
         run: |
+          # HOST=$(kubectl -n ${{ vars.NAMESPACE }} \
+          #   get ingress -o jsonpath='{.items[0].spec.tls[0].hosts[0]}')
+          # echo "APP_INGRESS_URL=$HOST" >> "$GITHUB_OUTPUT"
+
           echo "APP_INGRESS_URL=var_for_host_${{ vars.NAMESPACE }}" >> "$GITHUB_OUTPUT"
 
     outputs:
@@ -197,13 +299,15 @@ jobs:
           env:
             URL: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL }}
           run: |
+            # echo "Testing endpoint: https://$URL/live"
+            # curl https://$URL/live -s -k | jq -r .status | grep -iq live
             echo $URL
 
   ### new code for production env
   prod-deploy:
     #needs: dev-integration-testing   ### added
     needs: containerization   ### this steps depends on containerization
-    if: github.ref == 'refs/heads/main'
+    if: github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
     environment: 
       name: production     ### edited
@@ -218,9 +322,21 @@ jobs:
         with:
           version: 'v1.32.0'
 
+      # - name: Configure kubeconfig context
+      #   uses: azure/k8s-set-context@v3
+      #   with:
+      #     method: kubeconfig
+      #     kubeconfig: ${{ secrets.KUBECONFIG }}
+
       - name: Print kubeconfig secret
         run: |
           echo "Print kubeconfig secret --->${{ secrets.KUBECONFIG }}<--- "
+
+      # - name: Fetch Kubernetes Cluster Details
+      #   run: |
+      #     kubectl version --short
+      #     echo "------------------------------------------"
+      #     kubectl get nodes
 
       - name: Save Nginx Ingress IP
         id: ingress
@@ -246,10 +362,27 @@ jobs:
 
       - name: Create MongoDB Secret
         run: |
+          # kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
+          #   --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
+          #   --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
+          #   --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
+          #   --save-config \
+          #   --dry-run=client \
+          #   -o yaml | kubectl apply -f -
+
           echo "-namespace: ${{ vars.NAMESPACE }}\n-mongo uri: ${{ env.MONGO_URI }}\n-mongo username: ${{ env.MONGO_USERNAME }}\n-mongo pwd: ${{ secrets.MONGO_PASSWORD }}\n"
+
+      # - name: Deploy to Prod Environment   ### edited for production
+      #   run: |
+      #     kubectl apply -f kubernetes/produciton     ### deploy everything in prod dir   ### edited for production
+      
       - name: Set App Ingress Host URL
         id: set-ingress-host-address
         run: |
+          # HOST=$(kubectl -n ${{ vars.NAMESPACE }} \
+          #   get ingress -o jsonpath='{.items[0].spec.tls[0].hosts[0]}')
+          # echo "APP_INGRESS_URL=$HOST" >> "$GITHUB_OUTPUT"
+
           echo "APP_INGRESS_URL=var_for_host_${{ vars.NAMESPACE }}" >> "$GITHUB_OUTPUT"
 
     outputs:
@@ -259,10 +392,13 @@ jobs:
   prod-integration-testing:
     name: Prod Integration Testing   ### edited for production
     needs: prod-deploy   ### edited for production
+    # if: github.ref == 'refs/heads/master'   ### In my opinion it doesn’t make sense because this step needs on prod-deploy where we have the same condition
     runs-on: ubuntu-latest
     steps:
       - name: Test '/live' Endpoint
         env:
           URL: ${{ needs.prod-deploy.outputs.APP_INGRESS_URL }}   ### edited for production
         run: |
+          # echo "Testing endpoint: https://$URL/live"
+          # curl https://$URL/live -s -k | jq -r .status | grep -iq live
           echo $URL
